{{- if not .Values.config.existingJwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-jwt-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}

{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-mongodb-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
{{- end }}

{{- if .Values.mongodb.external.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-mongodb-external-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ .Values.mongodb.external.uri | b64enc | quote }}
{{- end }}
