apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
