environment: staging
replicaCount: 2

<<<<<<< HEAD
=======
image:
  repository: zahidbilal/ecommerce-backend
  tag: staging-latest
  pullPolicy: Always

# ============================================
# JWT & APPLICATION CONFIGURATION
# ============================================
>>>>>>> dev
config:
  jwtSecret: "staging-jwt-key-must-be-different-2024"
  logLevel: info

mongodb:
  enabled: true
  architecture: replicaset
  auth:
    rootPassword: "staging-root-789"
    username: "ecommerce_user"
    password: "staging-user-101"
  persistence:
    enabled: true
    size: 50Gi

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1000m

ingress:
  enabled: true
  hosts:
    - host: staging-api.ecommerce.com
