apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000

      - path: /
        pathType: Prefix
        backend:
          service:
            name: forntend-frontend   # <-- FIX THIS
            port:
              number: 80
