replicaCount: 1

image:
  repository: zahidbilal/ecommerce-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

config:
  apiUrl: "/api"
  environment: development
  enableAnalytics: "false"
  enableDebugTools: "true"

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 15

readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 5

autoscaling:
  enabled: false

monitoring:
  enabled: false
